# Generated by Django 4.1.3 on 2022-11-18 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll',
            new_name='rollno',
        ),
    ]
